/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false --env-interface Env src/worker-configuration.d.ts` (hash: 0b9f72ea79d71355eb531777bac8873a)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env {
		OAUTH_KV: KVNamespace;
		DB: D1Database;
		MEMORY_INDEX: VectorizeIndex;
		INDEX_QUEUE: Queue;
		AI: Ai;
		APP_BASE_URL: string;
		MCP_ROUTE: string;
		ZOHO_WORKDRIVE_API_BASE_URL: string;
		ZOHO_ACCOUNTS_BASE_URL: string;
		GITHUB_OAUTH_AUTHORIZE_URL: string;
		GITHUB_OAUTH_TOKEN_URL: string;
		GITHUB_OAUTH_USER_URL: string;
		GITHUB_OAUTH_EMAILS_URL: string;
		GITHUB_API_BASE_URL: string;
		GITHUB_OAUTH_SCOPES: string;
		WORKERS_AI_EMBEDDING_MODEL: string;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_BASE_URL" | "MCP_ROUTE" | "ZOHO_WORKDRIVE_API_BASE_URL" | "ZOHO_ACCOUNTS_BASE_URL" | "GITHUB_OAUTH_AUTHORIZE_URL" | "GITHUB_OAUTH_TOKEN_URL" | "GITHUB_OAUTH_USER_URL" | "GITHUB_OAUTH_EMAILS_URL" | "GITHUB_API_BASE_URL" | "GITHUB_OAUTH_SCOPES" | "WORKERS_AI_EMBEDDING_MODEL">> {}
}
